spring:
  devtools:
    restart:
      enabled: true
  application:
    name: springboot-demo
  profiles:
    active: dev
  aop:
    auto: true
    proxy-target-class: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
logging:
  level:
    com.zytech: info
    org.springframework: warn
management:
  endpoints:
    #暴露所有端点信息
    enabled-by-default: true
    web:
      exposure:
        #以web方式暴露
        include: '*'
  endpoint:
    health:
      show-details: always
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /user/*,/user/save
info:
  appName: zytech
  version: 1.0.0
zytech:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
